// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTYJ1oG_CyVU4m0qFmpx71MZS3lDMZ41A',
    appId: '1:995697513408:web:b46bd239e8265cfa946e25',
    messagingSenderId: '995697513408',
    projectId: 'todoapp-e82aa',
    authDomain: 'todoapp-e82aa.firebaseapp.com',
    storageBucket: 'todoapp-e82aa.appspot.com',
    measurementId: 'G-2WJZTFDDWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-3ik8gv5ttD4t-AjfPFL3IDPplNaz8U',
    appId: '1:995697513408:android:d568a8e814abdd15946e25',
    messagingSenderId: '995697513408',
    projectId: 'todoapp-e82aa',
    storageBucket: 'todoapp-e82aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU0m5YZJ5fQAxfHqV4DFbWQ0XFI9c0wiU',
    appId: '1:995697513408:ios:8882fa9d16204f7c946e25',
    messagingSenderId: '995697513408',
    projectId: 'todoapp-e82aa',
    storageBucket: 'todoapp-e82aa.appspot.com',
    iosClientId: '995697513408-9ol7vv33uomdrvv3a984ads51o6dpsp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU0m5YZJ5fQAxfHqV4DFbWQ0XFI9c0wiU',
    appId: '1:995697513408:ios:8882fa9d16204f7c946e25',
    messagingSenderId: '995697513408',
    projectId: 'todoapp-e82aa',
    storageBucket: 'todoapp-e82aa.appspot.com',
    iosClientId: '995697513408-9ol7vv33uomdrvv3a984ads51o6dpsp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
